'use strict';
const CASH_MAX=1000000000;
function cashMoney(value){return Number.isSafeInteger(value)&&value>=0&&value<=CASH_MAX;}
function cashParse(raw,optional=false){const s=String(raw).trim();if(optional&&s==='')return null;if(!/^\d+$/.test(s)||!cashMoney(Number(s)))throw Error('金額は0〜1,000,000,000円の整数で入力してください。');return Number(s);}
function cashRecord(date,id){return (state.cash?.collections||[]).find(r=>r.date===date&&r.customerId===id);}
function cashTotals(date){const opening=(state.cash?.days||[]).find(d=>d.date===date)?.opening??null;const records=(state.cash?.collections||[]).filter(r=>r.date===date);const total=records.reduce((sum,r)=>sum+(r.actual??0),0);return {opening,total,balance:opening===null?null:opening+total,records};}
function cashYen(n){return n===null?'未設定':n.toLocaleString('ja-JP')+'円';}
function cashStatus(r){return r?.actual===null||!r?'未登録':r.expected===null?'集金登録済み':r.actual>=r.expected?'集金完了':'未収あり';}
function cashSummary(date){const t=cashTotals(date);return `<section class="panel cash-panel"><h2>${date.replaceAll('-','/')} 財布・集金</h2><dl class="cash-totals"><dt>開始時残高</dt><dd>${cashYen(t.opening)}</dd><dt>当日の集金合計</dt><dd>${cashYen(t.total)}</dd><dt>計算上の財布残高</dt><dd>${cashYen(t.balance)}</dd></dl>${t.opening===null?'<p class="warning-box">開始時残高が未設定です。財布残高はまだ計算できません。</p>':''}<details ${t.opening===null?'open':''}><summary>${t.opening===null?'開始時残高を入力':'開始時残高を修正'}</summary><form id="cashOpeningForm" data-date="${date}"><label>財布の開始時残高（円）<input name="opening" inputmode="numeric" pattern="[0-9]*" required value="${t.opening??''}" autocomplete="off"></label><button type="submit">開始残高を保存</button></form></details><p class="small">開始残高＋その日の保存済み集金額で計算します。釣銭・支出は別記録しません。</p><p id="cashMessage" role="status" aria-live="polite"></p></section>`;}
function renderCashDelivery(c){const date=activeVisitDate(),r=cashRecord(date,c.id),expected=r?.expected??c.cashExpected??null;return cashSummary(date)+`<section class="panel cash-panel"><h2>この顧客の現金集金</h2><p>${cashStatus(r)}／請求予定額：${cashYen(expected)}</p>${expected!==null&&r?.actual!==undefined&&r.actual!==null?`<p>未収額：${cashYen(Math.max(0,expected-r.actual))}${r.actual>expected?'（予定額を超えて集金）':''}</p>`:''}<form id="cashCollectionForm" data-date="${date}" data-customer="${escapeHtml(c.id)}"><label>実際の集金額（円）<input name="actual" inputmode="numeric" pattern="[0-9]*" required value="${r?.actual??''}" autocomplete="off"></label><details><summary>請求予定額（分かる場合だけ）</summary><label>請求予定額（円）<input name="expected" inputmode="numeric" pattern="[0-9]*" value="${expected??''}" autocomplete="off"></label><p class="small">空欄なら未設定です。契約税込金額からは自動計算しません。</p></details><button type="submit">集金を保存</button>${r?.actual!==undefined&&r.actual!==null?'<button type="button" id="cashCancel">この集金を取り消す</button>':''}</form><p class="small">0円も保存できます。配達の「完了」「不在」と集金の登録は別操作です。金額を入力したら「集金を保存」を押してください。</p></section>`;}
function renderCashCheck(){const date=historyDate,t=cashTotals(date);return cashSummary(date)+`<section class="panel cash-panel"><h2>集金明細</h2>${t.records.length?t.records.map(r=>`<details><summary>${escapeHtml(r.name)}：${cashYen(r.actual)}・${cashStatus(r)}</summary><p>請求予定額：${cashYen(r.expected)}<br>実集金額：${r.actual===null?'未登録':cashYen(r.actual)}${r.expected!==null&&r.actual!==null?'<br>未収額：'+cashYen(Math.max(0,r.expected-r.actual)):''}</p>${state.customers.some(c=>c.id===r.customerId)?`<button type="button" data-cash-edit="${escapeHtml(r.customerId)}" data-cash-date="${date}">配達画面で修正</button>`:''}</details>`).join(''):'<p>この日の集金記録はありません。</p>'}<p class="small">日付は下の「確認する日」で変更できます。</p></section>`;}
async function cashSaveOpening(date,raw){if(!vaultUnlocked||visitSaving)return false;let opening;try{opening=cashParse(raw);}catch(e){alert(e.message);return false;}const next=clone(state);next.cash||={days:[],collections:[]};next.cash.days=next.cash.days.filter(d=>d.date!==date);next.cash.days.push({date,opening});return commitVisitState(next);}
async function cashSaveCollection(date,id,actualRaw,expectedRaw,cancel=false){if(!vaultUnlocked||visitSaving)return false;const c=state.customers.find(c=>c.id===id);if(!c)return false;let actual,expected;try{actual=cancel?null:cashParse(actualRaw);expected=cashParse(expectedRaw,true);}catch(e){alert(e.message);return false;}const next=clone(state);next.cash||={days:[],collections:[]};const records=next.cash.collections;const index=records.findIndex(r=>r.date===date&&r.customerId===id);const entry={date,customerId:id,name:c.name,expected,actual};if(index===-1)records.push(entry);else records[index]=entry;return commitVisitState(next);}
function wireCash(){
 document.getElementById('cashOpeningForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(await cashSaveOpening(f.dataset.date,f.elements.opening.value)){render();document.getElementById('cashMessage').textContent='開始残高を保存しました。';}});
 document.getElementById('cashCollectionForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(await cashSaveCollection(f.dataset.date,f.dataset.customer,f.elements.actual.value,f.elements.expected.value)){render();document.getElementById('cashMessage').textContent='集金額を保存し、財布残高を更新しました。';}});
 document.getElementById('cashCancel')?.addEventListener('click',async()=>{const f=document.getElementById('cashCollectionForm');if(confirm('この顧客・この日の集金を取り消しますか？')){const r=cashRecord(f.dataset.date,f.dataset.customer);if(await cashSaveCollection(f.dataset.date,f.dataset.customer,'',r.expected??'',true)){render();document.getElementById('cashMessage').textContent='集金を取り消しました。';}}});
 document.querySelectorAll('[data-cash-edit]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.cashDate!==activeVisitDate()){alert('別日の修正は、下の「配達する日の設定」で対象日を開始してから行ってください。訪問履歴は維持されます。');return;}currentCustomerId=b.dataset.cashEdit;setScreen('delivery');}));
}
